### ISSUE TITLE
Track-o-Bot Linux doesn't track games played

### ISSUE THREAD

**Issue by terzag** [BOSSoNe0013/track-o-bot#18]
Hello,
I play HearthStone one Ubuntu (15.04, GNOME 3 desktop) through Wine. I've compiled Track-o-Bot from source with Qt 4.5 but though it launches and the icon appears in the panel, it doesn't track my games. The Windows version installed in the same wine prefix as Battle.net tracks the games.

I've created the ~/.Hearthstone dir, in which I made the following symlinks:
- [wineprefix]/drive_c/users/myname/AppData/Local/Blizzard/Hearthstone/log.config to log.config ; note that I had to create the file (there wasn't even a Local dir in AppData) finding its content on the web
- [wineprefix]/drive_c/Program Files (x86)/Hearthstone/Hearthstone_Data/output_log.txt to output_log.txt
I've also made the second symlink as output_log as the GitHub presentation doesn't mention a .txt extension to that file.

In Track-o-Bot log (in the settings), it seems that it finds log.config but doesn't mention output_log(.txt). Is that normal? Did I get the right files for the symlinks?

EDIT: in fact, it seems to work since I've installed the Windows version (which fixed the logs maybe?). I thought it didn't because I hadn't noticed that the Windows version had created a different account for me. After checking my profile with the Linux version running, I can see the game I played.

**Comment by BOSSoNe0013** [comment]
Hi,
for the symlink it's output_log.txt, there's an error in the documentation.
The windows app does nothing more than the linux one. I'll try to reproduce your problem.
Thanks

**Comment by terzag** [comment]
Well, the problem is, I guess, that I misunderstood where the original logfile should have been and I think that it's needed by HearthStone to enable logging at all. As I said, I put the log.config in [wineprefix]/drive_c/users/[myname]/AppData/Local/Blizzard/Hearthstone/ and after installing the Windows version of Track-o-Bot, I saw that it created the file in [wineprefix]/drive_c/users/[myname]/Local Settings/Application Data/Blizzard/Hearthstone/

I'm not sure it's the only thing it did during its setup but the path seems more logical to me that this AppData directory. Maybe it depends of the Windows version simulated by Wine. Or maybe I'm completely mistaken as to what has changed.

**Comment by zutto** [comment]
I can confirm that the 
> WINEPREFIX/drive_c/users/WINEUSER/Local Settings/Application Data/Blizzard/Hearthstone/

location works if the track-o-bot isnt tracking the games from the /appdata/ directory.
