### ISSUE TITLE
Wrong account detected by Track-o-Bot on Linux

### ISSUE THREAD

**Issue by terzag** [BOSSoNe0013/track-o-bot#26]
Since the latests commits (I tried to recompile yesterday, I think it was still 0.6.1; I also tried just now with 0.6.2), Track-o-Bot gives me a new profile rather than getting my old one. I'm not sure how the profile is setup/detected, as there is no need to create an account on the Track-o-Bot website, but I haven't changed anything on my setup.

How do I fix this and not lose the stats of the 200-300 matches I had?

**Comment by BOSSoNe0013** [comment]
App configuration file has moved, restore your account with an existing account backup (import button on Account tab).
If you have no backup you can find the old configuration file and replace content of the new one. Use: 
locate Track-o-Bot.conf
