### ISSUE TITLE
Make Problems on Fedora 23 (also Ubuntu 14.04)

### ISSUE THREAD

**Issue by Ironchunk** [BOSSoNe0013/track-o-bot#30]
Hi,
i've tried to install track-o-bot on a Fedora 23 System. Asked the question on reddit but they forwarded to this location. I have followed the install instructions:

1. Install Qt5.5+ (http://doc.qt.io/qt-5/linux.html)
2. Download track-o-bot.zip && unzip
3. qmake ~/Qt/qmake ./track-o-bot/track-o-bot.pro
4. make (shows error's)

    make error's:
    make -f Makefile.Release
    make[1]: Entering directory '/home/ironchunk/Workspace/stuff/trackobot/track-o-bot-0.4.0'
    g++ -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DVERSION=\"0.4.0\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB - DQT_CORE_LIB -I. -I../../../../Applications/Qt/5.5/gcc_64/include -I../../../../Applications/Qt/5.5/gcc_64/include/QtGui - I../../../../Applications/Qt/5.5/gcc_64/include/QtNetwork -I../../../../Applications/Qt/5.5/gcc_64/include/QtCore -Itmp -I../../../../Applications/Qt/5.5/gcc_64/mkspecs/linux-g++ -x c++-header -c src/Local.h -o release/Track-o-Bot.gch/c++
    g++ -c -include release/Track-o-Bot -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DVERSION=\"0.4.0\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../../Applications/Qt/5.5/gcc_64/include -I../../../../Applications/Qt/5.5/gcc_64/include/QtGui -I../../../../Applications/Qt/5.5/gcc_64/include/QtNetwork -I../../../../Applications/Qt/5.5/gcc_64/include/QtCore -Itmp -I../../../../Applications/Qt/5.5/gcc_64/mkspecs/linux-g++ -o tmp/Main.o src/Main.cpp
    src/Main.cpp:1:24: schwerwiegender Fehler: QApplication: Datei oder Verzeichnis nicht gefunden
    Kompilierung beendet.
    Makefile.Release:1185: recipe for target 'tmp/Main.o' failed
    make[1]: *** [tmp/Main.o] Error 1
    make[1]: Leaving directory '/home/ironchunk/Workspace/stuff/trackobot/track-o-bot-0.4.0'
    Makefile:38: recipe for target 'release' failed
    make: *** [release] Error 2

Tried the same steps on a Ubuntu 14.04 VM (same error). Any suggestions?

Thanks for help.

Cheers

Ironchunk

**Comment by BOSSoNe0013** [comment]
Have you downloaded the zip file on this repo ? It's seems there's missing arguments for g++ (no QtWidgets inclusion).
Try cloning the repo on your computer instead of downloading the zip file.

Cheers

**Comment by Ironchunk** [comment]
Thanks that cloning instead of using the .zip helped. 

I have just one Problem left. You write on your documentation that we have to link the logs vom $WINEPREFIX/.../Hearthstone/Logs/log.config to ~/.Hearthstone/log.config  but i've no log folder:


/home/ironchunk/.wine/drive_c/Program Files (x86)/Hearthstone
[ironchunk@ironforge Hearthstone]$ ll
insgesamt 27340
-rwxrwx---. 1 ironchunk ironchunk  7560192  6. Dez 19:51 battle.net.dll
-rwxrwx---. 1 ironchunk ironchunk        0 15. Dez 21:03 bnet_client.log
-rwxrwx---. 1 ironchunk ironchunk      511 15. Dez 21:03 ConnectLog.txt
drwxrwx---. 3 ironchunk ironchunk     4096  6. Dez 19:51 Data
drwxrwx---. 2 ironchunk ironchunk     4096  6. Dez 19:53 DBF
-rwxrwx---. 1 ironchunk ironchunk  3053616  6. Dez 19:51 Hearthstone Beta Launcher.exe
drwxrwx---. 6 ironchunk ironchunk     4096 15. Dez 21:03 Hearthstone_Data
-rwxrwx---. 1 ironchunk ironchunk 16109544  6. Dez 19:51 Hearthstone.exe
-rwxrwx---. 1 ironchunk ironchunk        4  6. Dez 22:05 Launcher.db
-rwxrwx---. 1 ironchunk ironchunk   421200  6. Dez 19:51 msvcp100.dll
-rwxrwx---. 1 ironchunk ironchunk   773968  6. Dez 19:51 msvcr100.dll
drwxrwx---. 4 ironchunk ironchunk     4096  6. Dez 22:05 Strings


some changes from Blizzard?

Cheers

**Comment by BOSSoNe0013** [comment]
Hi,
as it's write in the doc, you have to create empty files if they not exists.
Cheers

**Comment by Ironchunk** [comment]
Hi,

yeah i get it after reading it twice. i was just confused about the Logs Folder. In your doc's its under this location: 

$WINEPREFIX/drive_c/Program\ Files/Hearthstone/Logs ~/.Hearthstone/Logs

and on my:

$WINEPREFIX/drive_c/users/WINEUSER/Local\ Settings/Application\ Data/Blizzard/Hearthstone/


Nevertheless it's seems to work now, thank you for your help.

Cheers

Ironchunk

**Comment by Ironchunk** [comment]
Okay, 

That was the wrong folder:

$WINEPREFIX/drive_c/users/WINEUSER/Local\ Settings/Application\ Data/Blizzard/Hearthstone/Logs 

These are just for errors and i cant find the game logs. 

There aren't on the location:

$WINEPREFIX/drive_c/Program\ Files/Hearthstone/Logs ~/.Hearthstone/Logs

Any suggestions?

Sorry for that :/

Cheers
