### ISSUE TITLE
0.7.1 is out :)

### ISSUE THREAD

**Issue by angrylinuxuser** [BOSSoNe0013/track-o-bot#35]
ps. is rank traking in broken? or was it removed and now reintroduced?

**Comment by BOSSoNe0013** [comment]
Merge done. For the rank tracking, i don't know as the code is still there so it should work.

**Comment by angrylinuxuser** [comment]
Its strange since tracking wasnt working for me for a while now. Didnt played ranked after update to 0.7.1 but i saw in log tab that some kind of ranking detection is there. Ill report back with more info. The pull request that you pulled in didnt worked for me in 0.7. Thats why i asked about rank tracking.

PS. if the first setting in track-o-bot points to logs dir then you need to change it to ~/.Hearhstone directory in order to record data.

**Comment by BOSSoNe0013** [comment]
Thanks for pointing me the problem with the default path :) I'll have a look on ranking tracking.
