### ISSUE TITLE
0.8 is out

### ISSUE THREAD

**Issue by angrylinuxuser** [BOSSoNe0013/track-o-bot#40]
overlay thingy is comming.

**Comment by BOSSoNe0013** [comment]
merge done but there's something wrong with the overlay, i've to perform investigations ;)

**Comment by BOSSoNe0013** [comment]
done :)

**Comment by angrylinuxuser** [comment]
thanks :) its working nice however  there are few issues that id like to mention:
this one is weird and it looks like track-o-bot is crashing with clang in strlen()... and it gave me a 20 minute headscratching session (not your fault but funny to mention) switched to gcc and it works like a charm
2nd is that while hearthstone is running (even minimized or on the other desktop) i cant click apps that are under "invisible" overlay.
3rd that i noticed is that overlay is not rendered correctly (cut off) when hearthstone app is not wide enough (this one is kinda understandable) :)

i hope at least 2nd is fixable :)

**Comment by BOSSoNe0013** [comment]
Hi,
i'ven't try to use clang, so if you find a solution for the crash and want to push a patch, you're welcome ;)
For the second problem, i've also a multi-screen config (3 screens and an nvidia GPU) and the overlay follow the app window and is even minimized as HS is. The position and size of the overlay is handled by a timer so it's not done instantly.
I've made the overlay smaller than the original as we can't passthrough clicks to an underlying wine application under X11. You can see the overlay by commenting this line:
https://github.com/BOSSoNe0013/track-o-bot/blob/master/src/ui/Overlay.cpp#L182
For the third, i think i can set a minimum width but in this case a part of the overlay may be displayed outside the HS window (not a real problem when playing windowed, but in fullscreen...).

Thanks again for your feedback, have a nice day :)

**Comment by angrylinuxuser** [comment]
Right i missed that the minimization hides the overlay because of 3sec update interval in linuxwindowcapture:P
There still is the issue when i switch  to other virtual desktop then overlay grabs input from other windows in the area it resides so Ive made some changes to fix this (you can grab them from my repo to see what i did - probably a big hack and done in wrong plance but it works for me) I check if the hs is focused. if it is then show the overlay

**Comment by angrylinuxuser** [comment]
I play in windowed mode and alt-tab a lot beetween hs and browser or other programs so ovelay displayed data when mouse was over the trigger areas (before last commit it grabbed input also). So this time i managed to hide overlay when window isnt focused. Maybe it will be usefull. Changes are in my fork. Can you take a look at it?
