### ISSUE TITLE
Trouble running under Wine

### ISSUE THREAD

**Issue by wavecycle** [BOSSoNe0013/track-o-bot#57]
Hi, I'm still a linux noob so I'm trying to run the app through Wine rather than the native version. 

I've installed it through PoL in the same prefix as HS and everything seems to work fine with the install. Afterwards I run the app and I can see the icon in the taskbar but when I right-click on it nothing happens. Any idea what is wrong? 

Thanks

**Comment by wavecycle** [comment]
Sorry, only saw afterwards there is a subreddit, will ask there

**Comment by angrylinuxuser** [comment]
why are you trying to run it via wine when you can have native app?

**Comment by wavecycle** [comment]
I'm a noob user and hitting install through PoL looked simpler tbh

**Comment by angrylinuxuser** [comment]
I think that you might have some issues with overlay if you make it run under wine. But if you want to build native app just ask. Ill try to help you out.

**Comment by wavecycle** [comment]
Thank you, I appreciate it :)

I am using [these instructions](https://github.com/BOSSoNe0013/track-o-bot). I have installed qt5.5 alright I think. Next step: 

CTrack-o-Bot now relies on Power.log, Zone.log, Asset.log and Bod.log so you have to create symlinks of the Hearthstone's logs folder ("WINEPREFIX/drive_c/Program Files/Hearthstone/Logs") and log.config ("WINEPREFIX/drive_c/users/WINEUSER/Local Settings/Application Data/Blizzard/Hearthstone/", create file if not exists) in the newly created folder eg:
ln -s $WINEPREFIX/drive_c/Program\ Files/Hearthstone/Logs ~/.Hearthstone/Logs

ln -s $WINEPREFIX/drive_c/users/WINEUSER/Local\ Settings/Application\ Data/Blizzard/Hearthstone/log.config  ~/.Hearthstone/log.config


So I entered these two lines, is that correct:

1. ln -s ~/.PlayOnLinux/wineprefix/battle.net/drive_c/Program\ Files/Hearthstone/Logs ~/.Hearthstone/Logs

2. ln -s ~/.PlayOnLinux/wineprefix/battle.net/drive_c/Program\ Files/Hearthstone/Logs ~/.Hearthstone/Logs

Then the next steps are "qmake" and "make" with no details on what to do...I have no idea.

**Comment by angrylinuxuser** [comment]
those instructions are old and have to be updated. You dont have to create those links or ~/.Hearthstone directory now. If you compile the track-o-bot and it will run fine then go to settings and set wine prefix directory and hearthstone directory and it should work from there.

On this page are updated instructions: https://github.com/angrylinuxuser/track-o-bot/tree/more_fixes

**Comment by wavecycle** [comment]
Ok, so I installed the dependancies:

sudo apt-get install build-essential libglu1-mesa-dev libx11-dev libxext-dev libxfixes-dev

But then it says:

Build Instructions:
qmake
make

I don't understand that. There aren't even any arguments for the qmake/make.

Thanks

**Comment by angrylinuxuser** [comment]
have you got the sources for the project? if not then do:

sudo apt-get install git

this will install git after that in terminal do:
cd ~
( change dir to home dir) then download the source code via git:
git clone https://github.com/BOSSoNe0013/track-o-bot.git

when it will finish downloading then enter track-o-bot directory
( cd track-o-bot )
and do qmake after that do make

**Comment by wavecycle** [comment]
ok, all the steps worked except when I do the "qmake" in the track-o-bot directory i get:
"qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory"

**Comment by angrylinuxuser** [comment]
try running:
qtchooser -run-tool=qmake -qt=5
instead of qmake

If it fails please give me more info on your setup: what version of ubuntu and 32vs64bit and how did you install qt5.5+

**Comment by angrylinuxuser** [comment]
do you have installed qtbase5-dev ?

**Comment by wavecycle** [comment]
thanks for the help angry guy :)

i install through the app I downloaded from https://www.qt.io/download/

its a downloader that manages the install for 5.6

I tried the qtchooser but i still get the same error msg:
qtchooser: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/qmake': No such file or directory

I'm running ubuntu 16.04 (64 bit). I am not sure if I did the qtbase5-dev, how do i check?

**Comment by angrylinuxuser** [comment]
well do: sudo apt-get install qtbase5-dev ( this package is required to build qt programs - i think ubuntu has qt5 by default )
then repeat
qtchooser -run-tool=qmake -qt=5

or you could try running (assuming you installed qt5.6 into Qt directory in your home )
~/Qt/5.6/gcc_64/bin/qmake

**Comment by wavecycle** [comment]
ok :) installed the qtbase5, ran the qtchooser line and it worked. followed with "make" and it has run now. what next?

**Comment by angrylinuxuser** [comment]
Try running track-o-bot ( should be in build subdirectory)  and configure paths in settings for wine prefix and hearhtstone directory

if you want install it system wide then do
sudo make install

or you can juts copy executable to some directory and run it without installing it

**Comment by wavecycle** [comment]
It works!!! Thank you for helping with my first build...will be a bit easier next time having done this now :)

**Comment by angrylinuxuser** [comment]
no problem :)
