### ISSUE TITLE
Options window title doesn't have a close button on Mate

### ISSUE THREAD

**Issue by terzag** [BOSSoNe0013/track-o-bot#59]
Using Ubuntu Mate 16.04 (Mate 1.12). Not sure it was the case before but Track-o-Bot's option window title doesn't have a close button. To close it, I have to right-click on it to show the context menu or press alt + F4.

Haven't tried with other WMs or DEs.

**Comment by angrylinuxuser** [comment]
it might to be mates fault cuz on kde it runs fine. Ill install ubuntu in vm later today and see if ill be able to reproduce/figure out whats wrong.

**Comment by terzag** [comment]
Ok, thanks.

I'm not sure how this is all set, if it checks the DE for specific code or something like that but just in case, Mate is a Gnome 2 fork that renamed the "Metacity" WM to "Marco".

**Comment by angrylinuxuser** [comment]
i've built ToB within mate vm and i have close button

**Comment by terzag** [comment]
Damn. Sorry, that's another case of issue on my side, I should have checked more thoroughly. It seems to happen only with the theme I'm using (Arc Theme: https://github.com/horst3180/arc-theme) and works fine with the original Ambiant-MATE theme or a bunch of others.
