### ISSUE TITLE
Errors in french translation

### ISSUE THREAD

**Issue by terzag** [BOSSoNe0013/track-o-bot#60]
I've noticed a small typo in the french translation of ToB ("Survollez" should be "Survolez") and a few odd translations.

Not sure if there's a better way to address these than through a bug report?

**Comment by angrylinuxuser** [comment]
BOSSoNe0013 did french translations:) blame him:)

Bug report is the right place :) So if you find some odd translations putt them in bug report im sure BOSSoNe0013 will update them.

**Comment by terzag** [comment]
Ok. :)

So apart from that typo on "Survolez", I think it would be better to change the following:

> "Utilisez l'exportation pour effectuer une sauvegarde de votre compte ou afin de l'importer sur un autre terminal. Vous pouvez utiliser le même compte sur plusieurs terminaux simultanément."

to:

> "Utilisez l'exportation pour effectuer une sauvegarde de votre compte ou afin de l'importer sur un autre ordinateur. Vous pouvez utiliser le même compte sur plusieurs ordinateurs simultanément."

(The word "terminal", though technically correct, is rather used in France for client machines that were used for remote access to a server 30-40 years ago. "Ordinateur(s)" would be better as it's the translation for "computer(s)". Or even "machine(s)" for a more generic term.)

There's also the following nagging me:

> "Afficher les données complémentaires en jeu"

It's the option that displays the tracker in game. Not sure what the original english string is but "données complémentaires" ("complementary data") isn't really describing the option properly. A better name would be something like:

> "Afficher le suivi des cartes en jeu"

("Display the cards tracked in game")

**Comment by angrylinuxuser** [comment]
If you can find English original strings along with the translated strings in i18n directory ( .ts files )

**Comment by terzag** [comment]
Ok, so that would be these:

<location filename="../src/ui/SettingsWidget.ui" line="224"/>
<source>Hover over your or your opponent&apos;s deck to see which cards were drawn or played.</source>
<translation>Survolez votre pioche ainsi que celle de votre adversaire pour afficher la liste des cartes piochées ou jouées.</translation>


<location filename="../src/ui/AccountWidget.ui" line="115"/>
<source>Use export to back up your account or to import it on another device. You can use the account on multiple devices simultaneously. </source>
<translation>Utilisez l'exportation pour effectuer une sauvegarde de votre compte ou afin de l'importer sur un autre ordinateur. Vous pouvez utiliser le même compte sur plusieurs ordinateurs simultanément.</translation>

<location filename="../src/ui/SettingsWidget.ui" line="217"/>
<source>Enable in-game overlay</source>
<translation>Afficher le suivi des cartes en jeu</translation>

But apart from the first one which is a real typo, the others are more a personal advice. "Machine(s)" might be a more proper translation than "Computer(s)" for "Device(s)". As for the third one, the original english version isn't that clear either (maybe change "Enable in-game overlay" to something like "Display the cards tracked in game"?).

**Comment by BOSSoNe0013** [comment]
Hi,
thanks for the feedback. I'm ok with one and three but as we can install ToB on devices like mobile phone, the word Terminal has much sense than computer and machine (too generic).

**Comment by terzag** [comment]
Track-o-Bot is installable on mobile phones?

**Comment by BOSSoNe0013** [comment]
Yes there's an app on the Google Play store that allows you to see your
stats.

**Comment by BOSSoNe0013** [comment]
https://play.google.com/store/apps/details?id=com.trackobot.android

Le mer. 15 juin 2016 à 13:04, Cyril Bosselut <bossone0013@gmail.com> a
écrit :

> Yes there's an app on the Google Play store that allows you to see your
> stats.
>
