### ISSUE TITLE
Can't view profile

### ISSUE THREAD

**Issue by wavecycle** [BOSSoNe0013/track-o-bot#61]
If I right-click on the taskbar icon and select "Open Profile" the app launches a blank browser with no URL..so I don't seem to be able to access my profile/stats.

The app is installed (Ubuntu 16.04, 64-bit, native) and seems to be running fine in terms of showing the overlay and being able to access the settings from the taskbar icon. I have set the prefix and HS directory.

I first tried to run track-o-bot through wine in the prefix and that didn't work. Now I am running it natively in the same prefix and I have uninstalled the windows install. Maybe this has something to do with it?

Thank you

**Comment by angrylinuxuser** [comment]
Go to settings and enable debug mode then go to log tab. While the tab is showed click on the show profile in the taskbar) Do you see something like "Received {"url":"https://trackobot.com/profile?........"} ? Copy this url and put it in a browser. If it asks you for a password do in terminal:

cat ~/.config/spidy.ch/Track-o-Bot.conf

and copy username and password from there

I Had similar thing happen to me yesterday for the first time. This is strange maybe something changed on the website side. Ive noticed one thing. that url changes every time i click on show profile.

**Comment by wavecycle** [comment]
Thanks, that all worked and I am logged into my profile now.

Any idea why the browser is not receiving the URL? When I copy-pasted it from the log it took me to the profile login page.

**Comment by angrylinuxuser** [comment]
Don't know. Yesterday i installed mate ubuntu in vm and it worked fine without any probems. And does it work now fine if you click open profile?

**Comment by wavecycle** [comment]
No, still not. But I have favourited the page in my browser so I can go there directly.

**Comment by angrylinuxuser** [comment]
Strange. For me it only happened once and now it's ok. Can you change the default browser in ubuntu settings and try again?

**Comment by angrylinuxuser** [comment]
Works for me fine in vm. It must be some strange issue on your side or some kind of misconfiguration.

**Comment by wavecycle** [comment]
Weird. I set the default browser to firefox and then it works. Same for the ubuntu browser. Set it back to Chrome and it stops working again.

No worries, I'll just access the profile through the bookmark I set. 

Thanks again for the help :)

**Comment by angrylinuxuser** [comment]
It looks like it's a problem on your side so could you please close this bug report?
