### ISSUE TITLE
Can't open cardxml0.unity3d

### ISSUE THREAD

**Issue by orangejake** [BOSSoNe0013/track-o-bot#67]
Hi, I've been trying to configure this to work, and have gotten it so I don't think the debug logs are reporting any issues, but the GUI still fails to appear ingame (expect for a slightly darker rectangular patch where I'm assuming it's supposed to go).

Before, I was having issues finding the correct folders to point it towards in the settings.  I'm using PlayOnLinux, and have set:

`/home/mark/.PlayOnLinux/wineprefix/hearthstone`

for the Wine folder, and:

`/home/mark/.PlayOnLinux/wineprefix/hearthstone/drive_c/Program\ Files/Battle.net`

for the Game folder.

For the [logs](https://github.com/BOSSoNe0013/track-o-bot/files/560279/normallogs.txt) not in debug mode, nothing too interesting seems to be happening.  It says `Starting HearthstoneLogTracker` for a variety of locations, and when I open Hearthstone I get the additional message:

`[21:19:39] INFO: File /home/mark/.PlayOnLinux/wineprefix/hearthstone/drive_c/users/mark/Application Data/Battle.net/55b6185e.config`

which doesn't jump out at me as being a problem.

After this, I turned on debug mode and repeated the process.  The [logs](https://github.com/BOSSoNe0013/track-o-bot/files/560278/debuglogs.txt) for that are here.

This seems to do the same things as the normal mode untill I open Hearthstone, where it starts having the following appear repeatedly:

`[21:09:08] DEBUG: Region detected:`
`[21:09:08] DEBUG: Unload Card DB`
`[21:09:08] DEBUG: Load Card DB`
`[21:09:08] DEBUG: Locale = enUS`
`[21:09:08] DEBUG: Couldn't open /home/mark/.PlayOnLinux/wineprefix/hearthstone/drive_c/Program Files/Battle.net/Data/Win/cardxml0.unity3d`

I'm guessing the issue is either from setting the Wine and Game folders incorrectly, or something to do with the last line I've quoted from the log.  I've included the full logs for both tries.

**Comment by sdc111** [comment]
I have this functioning and it did take me a bit to figure out proper folders. Here's what I have:

Wine = /home/USERNAME/PlayOnLinux's virtual drives/battlenet
Game = /home/USERNAME/PlayOnLinux's virtual drives/battlenet/drive_c/Program Files/Hearthstone

**Comment by orangejake** [comment]
That seemed to fix a number of things, but I still have the following issues. I played a game and included the [log file](https://github.com/BOSSoNe0013/track-o-bot/files/560798/louddebug.txt) from it.

The two issues I had were:

1. The in-game GUI wasn't showing up at all.  The previous "shadow" where it was supposed to be was gone also.
2. The results weren't uploaded.

The second issue is clearly displayed at the end of the log as:

`[15:22:17] INFO: Uploading result...`
`[15:22:17] ERROR: There was a problem uploading the result (Reply 8, HTTP 0). Will save the result locally and try again later.`
`[15:22:19] ERROR: There was a problem creating an auth token. Error: 8 HTTP Status Code: 0`
`[15:22:24] ERROR: There was a problem creating an auth token. Error: 99 HTTP Status Code: 0`
`[15:24:15] ERROR: There was a problem creating an auth token. Error: 99 HTTP Status Code: 0`

I can't seem to find anything in the log pointing to why the in-game overlay isn't working.  I've double-checked that it's enabled, so that isn't it.  I'm currently going to try restarting my system to see if that fixes it.

**Comment by orangejake** [comment]
Restarting made the tracking itself work (and it uploaded to my profile successfully).

Now, the only "issue" (if there's no solution it isn't the biggest deal) is some weird shading that's happening while Hearthstone is the active window.

Here's a picture when HS is the active window.
![hsactivewindow](https://cloud.githubusercontent.com/assets/15336079/19840649/151600fe-9eb8-11e6-8307-230f850291ca.png)

And here's a picture when HS is an inactive window.
![hsunactivewindow](https://cloud.githubusercontent.com/assets/15336079/19840652/197e6d16-9eb8-11e6-97b7-c773ece4a1f1.png)

**Comment by BOSSoNe0013** [comment]
Hi,
I think your compositor is creating shadows under windows and that's you
are viewing  (overlay is displayed on a transparent window floating over
The HS window).
Hope this helps

Le dim. 30 oct. 2016 à 23:47, orangejake <notifications@github.com> a
écrit :

**Comment by sdc111** [comment]
No help for you there. I don't experience that on my old GeForce GT 630M running with driver version 367.57.

**Comment by orangejake** [comment]
It appears my compositor is Compton.  I haven't messed with it before at all, so I'll probably try to in a few days.

It seems like I'm going to want to edit the compton config to to stop shadows being drawn on the track-o-bot window, similar to what [the wiki talks about here](https://wiki.archlinux.org/index.php/Compton#Disable_shadowing_of_some_windows). Does this seem reasonable?

**Comment by BOSSoNe0013** [comment]
Yes this is what you have to do

Le lun. 31 oct. 2016 à 00:07, orangejake <notifications@github.com> a
écrit :

**Comment by orangejake** [comment]
How do I specify the Track o Bot window?  I see that some windows are specified via things such as `"name = 'Notification'"` or `"class_g = 'Conky'"`.  How do I specify trackobot?

**Comment by BOSSoNe0013** [comment]
The window name should be "Track-o-Bot" (you can use xwininfo or xprop apps to get it but it's a bit difficult as the window is hidden when HS lose focus).
