### ISSUE TITLE
No overlay or tracking - Ubuntu install

### ISSUE THREAD

**Issue by wavecycle** [BOSSoNe0013/track-o-bot#71]
I've compiled an install using: https://github.com/BOSSoNe0013/track-o-bot.git

the build seems to work fine as i can check the settings, set  the HS directory and I can view the log and see the game starting up or closing. however there is no overlay in the game and if i view the web profile there is no game tracking.

Any help? Thanks :)

**Comment by angrylinuxuser** [comment]
Works for me.
Have you properly configured ToB? wine prefix and hs dir?
Could You enable debug mode in settings and post logs from at least one game?

**Comment by wavecycle** [comment]
I'm sorry, my bad I had the wrong wine folder, it is working great now :)
