### ISSUE TITLE
Discovered cards (from Drakonid operative and netherspite librarian) aren't being picked up

### ISSUE THREAD

**Issue by wavecycle** [BOSSoNe0013/track-o-bot#78]
I've seen this several times playing against priest when they use drakonid operative or netherspite librarian to get more drakonid operatives but on the overlay the number played remains at 2x even though they have played 4-5.

**Comment by BOSSoNe0013** [comment]
Hi,
i think this issue is non Linux specific and should be reported to the main [ToB project](https://github.com/stevschmid/track-o-bot)
Thanks
