### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by nelson-uruworks** [BOSSoNe0013/track-o-bot#79]
Hi, I cloned the repository, installed the required libraries, and when I run qmake, make, I get the following error:

g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o Autostart.o src/Autostart.cpp
src/Autostart.cpp:3:24: fatal error: QApplication: No such file or directory
compilation terminated.
Makefile:625: recipe for target 'Autostart.o' failed
make: *** [Autostart.o] Error 1

**Comment by angrylinuxuser** [comment]
Hmm some issues with includes. From what i can tell widgets arent included extras network xml
What distro are you running?

**Comment by BOSSoNe0013** [comment]
I think your Qt version is too old. Check the frame for the minimum version.

Le ven. 23 déc. 2016 à 21:13, angrylinuxuser <notifications@github.com> a
écrit :

**Comment by nelson-uruworks** [comment]
I ran the command as per the readme:
sudo apt-get install build-essential qt5-default qtbase5-dev libqt5x11extras5-dev libxcb1-dev libxcb-icccm4-dev

I'm on Ubuntu 16.04 LTS on x64, and the version I get on $ qmake --version is
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu

Thank you

**Comment by angrylinuxuser** [comment]
Intstalled ubuntu 16.04 in vm and from fast testing it looks like Makefile got mixed up somehow ( was able to reproduce this only once first by running qmake test.pro then qmake track-o-bot.pro ) Not gona dig into this since recloning repo then runing qmake track-o-bot.pro and make again works.

**Comment by nelson-uruworks** [comment]
You were right, starting from scratch on a new clone of the repo worked.
Thank you for taking a look into it!
