### ISSUE TITLE
No overlay, just black screen

### ISSUE THREAD

**Issue by mauriciopasquier** [BOSSoNe0013/track-o-bot#82]
First things first: thanks for working on this.

I just cloned and compiled from master, everything went great. Installed it, started it, it tracked some games, uploaded stats, tray icon working great, etc. But when I enabled the overlay, It just showed a black screen. I restarted everything, with overlay enabled already: same thing. Tried without fullscreen and nothing.

A weird thing that happens is that I can see the game when another window is focused (still no overlay though).

I'm using archlinux. I have this dependencies versions:

- qt5-base: **5.7.0**
- qt5-x11extras: **5.7.0**
- mesa: **13.0.0**
- xcb: **1.12** (the package is `libxcb`)
- xcb-icccm: I think in archlinux the package with this library is `xcb-util-wm` which is **0.4.1**

Please help me debug this thing! I think it could be an issue that I'm using [awesome](https://en.wikipedia.org/wiki/Awesome_(window_manager)). Any thoughts?

**Comment by angrylinuxuser** [comment]
Yes its awaesome. Overlay requires compositing window manager.

**Comment by mauriciopasquier** [comment]
Ok, first time I hear about compositing and stuff. Just running [compton](https://wiki.archlinux.org/index.php/Compton) for the session resolved the issue. Thanks!
