### ISSUE TITLE
ToB crashes at HS launch

### ISSUE THREAD

**Issue by Zbradaradjan** [BOSSoNe0013/track-o-bot#90]
Hi, so I installed ToB, it went well, but when I launch Hearthstone it just crash. I launched it from console to see the crash text, here it is : 
Track-o-Bot: src/HearthstoneCardDB.cpp :114 : void HearthstoneCardDB::LoadJson():  l'assertion « error.error == QJsonParseError::NoError » a échoué.
Abandon (core dumped)

Thanks

**Comment by angrylinuxuser** [comment]
Could You delete json file from ~/.local/share/spidy.ch/Track-o-Bot and see if it crashes again? If yes please enable debug mode and paste here contents of Track-o-Bot.log from the same directory.

**Comment by Zbradaradjan** [comment]
So I deleted that json file, launched the game and it crashed again. Here is the Track-o-Bot.log
[DebugLog.txt](https://github.com/BOSSoNe0013/track-o-bot/files/938801/DebugLog.txt)

**Comment by angrylinuxuser** [comment]
Ok so this issue is related to the enGB language You are using. This is upstream issue developer knows about. Try setting enUS as language for game in bnet settigns. This should fix it.

**Comment by Zbradaradjan** [comment]
Ok so it doesn't crash anymore, but there's no overlay.

**Comment by angrylinuxuser** [comment]
Strange. For good mesure delete json files again restart ToB and hs ( and double check if u have enabled overlay :) ) if issue is still present please play one or two rounds against ai then post log and json file

**Comment by Zbradaradjan** [comment]
All right, I'm trying this. Is there an order when launching ToB and HS ?

**Comment by angrylinuxuser** [comment]
there shouldnt be any need for ordering try running tob frist then hs

**Comment by Zbradaradjan** [comment]
Oh, you said 1 or 2 rounds. Played a full game against AI. Still no overlay, triple checked that the option was ticked.

[DebugLog.txt](https://github.com/BOSSoNe0013/track-o-bot/files/938874/DebugLog.txt)

**Comment by angrylinuxuser** [comment]
Cards are loaded so this side of the issue is resolved. 
Just to be sure ( sorry bout that  :) )  - Did you hover mouse over unplayed cards ( decks on left side near button ) to show the overlay?
What distro are you using and what window manager?

**Comment by Zbradaradjan** [comment]
I didn't hover my mouse over anything, because there's nothing to hover over (Over)
There's really nothing different than when ToB is not active.
I'm on XUbuntu 16.04 and I'm not sure what window manager I use. I didn't install anything, so I guess the default one ? Maybe that's the issue, I didn't install any ?

**Comment by angrylinuxuser** [comment]
when ToB Hearthstone are running you can show overlay trigger area is hidden
you should be able to see it if you do this: 
https://trackobot.com/assets/screenshot_overlay-d320357486ea4653800fc78767b21fd71ddb00830bd4e3554b77b07b623c1c0c.jpg

**Comment by Zbradaradjan** [comment]
Ooh dumb me, I forgot that you had to hover. All right, problem solved, thanks !
