### ISSUE TITLE
Track-o-Bot crashes when HS starts

### ISSUE THREAD

**Issue by terzag** [BOSSoNe0013/track-o-bot#93]
Since the recent HearthStone update, Track-o-Bot crashes with the following error as soon as HearthStone is launched:

`Track-o-Bot: src/HearthstoneCardDB.cpp :114 : void HearthstoneCardDB::LoadJson():  l'assertion « error.error == QJsonParseError::NoError » a échoué.`

**Comment by angrylinuxuser** [comment]
change ingame language from engb to enus

**Comment by terzag** [comment]
I'm not sure what you mean: the language of HearthStone? I play in french, I won't switch to english...

**Comment by angrylinuxuser** [comment]
then the card db is corrupted
delete ~/.local/share/spidy.ch/Track-o-Bot/cards_19506_enUS.json and restart

**Comment by terzag** [comment]
Seems to work, thanks. (In my case, it was cards_19506_frFR.json)

Is that file the current database of cards for ToB? I also have a cards_18792_frFR.json, do I delete it too?

**Comment by angrylinuxuser** [comment]
If you want. those are db for old patches. They are deprecated at this point.

**Comment by terzag** [comment]
Ok, done.

**Comment by angrylinuxuser** [comment]
please close this bug report if issue is resolved
