### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hoyeeleo** [BOSSoNe0013/track-o-bot#94]
the error is introduced by commit b491b1ae55aea2f37664356aba944f6bdcd94536 

==16633== Process terminating with default action of signal 11 (SIGSEGV)
==16633==  Access not within mapped region at address 0x8
==16633==    at 0x674A62D: QSettings::value(QString const&, QVariant const&) const (in /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.7.1)
==16633==    by 0x157797: WineBottle::ReadRegistryValue(QString const&) const (WineBottle.cpp:114)
==16633==    by 0x1579B9: WineBottle::HearthstoneInstallLocation() const (WineBottle.cpp:126)
==16633==    by 0x11AF38: Hearthstone::DetectHearthstonePath() const (Hearthstone.cpp:277)
==16633==    by 0x14B919: Settings::HearthstoneDirectoryPath() const (Settings.cpp:118)
==16633==    by 0x138944: HearthstoneLogTracker::HearthstoneLogTracker(QObject*) (HearthstoneLogTracker.cpp:38)
==16633==    by 0x152B14: Trackobot::Trackobot(int&, char**) (Trackobot.cpp:42)
==16633==    by 0x119785: main (Main.cpp:5)

**Comment by angrylinuxuser** [comment]
try this if it works ill submit for inclusion: https://github.com/angrylinuxuser/track-o-bot

**Comment by hoyeeleo** [comment]
it works! thanks!
